project:
  type: website
  output-dir: docs

website:
  title: "Multnomah Cancer Deaths By Age"
  search: false
  sidebar:
    style: "docked"
    contents:
      - href: titlePage.qmd #Dianara
        text: Title Page
      - href: abstract.qmd #person B
        text: Abstract
      - href: background.qmd #Alaniya
        text: Background
      - href: methods.qmd #Dianara and Alaniya
        text: Methods
      - href: Results.qmd #Dianara 
        text: Results
      - href: conclusion.qmd #Dianara
        text: Conclusion

format:
  html:
    theme: cosmos
    css: style.css
    toc: true
    code-fold: true