project:
  type: website
  output-dir: docs

website:
  title: "Multnomah Cancer Deaths By Age"
  search: false
  sidebar:
    style: "docked"
    contents:
      - href: index.qmd
        text: Title Page
      - href: abstract.qmd 
        text: Abstract
      - href: background.qmd
        text: Background
      - href: methods.qmd 
        text: Methods
      - href: Results.qmd  
        text: Results
      - href: conclusion.qmd 
        text: Conclusion

format:
  html:
    theme: cosmos
    css: style.css
    toc: true
    code-fold: true